[app]
name = "vrai-ffmpeg-processor"
description = "VoiceRecorder AI FFmpeg processing service on Modal.com"

[build]
dockerfile = "Dockerfile"

[secrets]
custom-secret = [
    "FIREBASE_SERVICE_ACCOUNT_KEY",
    "OPENAI_SECRET",
    "openai_secret",
    "AWS_ACCESS_KEY_ID",
    "AWS_ACCESS_PW",
    "S3_BUCKET_NAME",
    "DATABASE_URL",
    "NEXT_PUBLIC_CLIENT_FIREBASE_CONFIG",
    "aws_access_key_id",
    "aws_access_pw",
    "s3_bucket_name",
    "sieve_api_key"
]

[resources]
cpu = 1.0
memory = 1024
timeout = 900

[endpoints]
health = "/health"
process = "/trim-and-transcribe"
