name: Deploy Vrai Lambda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 16
jobs:
  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      
      - name: Install Serverless Framework
        run: npm install -g serverless
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install additional dev dependencies
        run: |
          npm install --save-dev serverless-plugin-warmup
          npm install --save-dev serverless-plugin-warmup-ts-bridge
          npm install --save-dev serverless-plugin-include-dependencies
      
      - name: Clean ffmpeg directory
        run: rm -rf ffmpeg/*
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - name: Deploy to AWS Lambda
        run: serverless deploy --stage production
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${[object Object]secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          s3_name: ${{ secrets.s3_bucket_name }}
          openai_secret: ${{ secrets.openai_secret }}
          aws_access_key_id: ${{ secrets.aws_access_key_id }}
          aws_access_pw: ${{ secrets.aws_access_pw }}
          NEXT_PUBLIC_CLIENT_FIREBASE_CONFIG: ${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_CONFIG }} 